#!/bin/sh
. Common
$LEAVE

title "Write Flash from file in Intel HEX format (explicit)"
random_flash _flash
{
    echo :05000000AB12FF0088B7
    echo :00000001FF
} | prog -w -5 -i -
prog -r | uniq >_out
expect <<EOF
AB 12 FF 00 88 00 00 00
00 00 00 00 00 00 00 00
EOF
