#!/bin/sh
. Common
$LEAVE

title "Set protection partially to F (full byte), retrieve"
random_file _file
prog -w -b -5 -f - _file 2>_out <<EOF
FFFFFFFF
EOF
prog -s -s >>_out
expect <<EOF
warning: protection mode F does not protect
warning: padding protection bits to full Flash size with U
FFFFFFFF UUUUUUUU UUUUUUUU UUUUUUUU UUUUUUUU UUUUUUUU UUUUUUUU UUUUUUUU
FFFFFFFF UUUUUUUU UUUUUUUU UUUUUUUU UUUUUUUU UUUUUUUU UUUUUUUU UUUUUUUU
FFFFFFFF UUUUUUUU UUUUUUUU UUUUUUUU UUUUUUUU UUUUUUUU UUUUUUUU UUUUUUUU
FFFFFFFF UUUUUUUU UUUUUUUU UUUUUUUU UUUUUUUU UUUUUUUU UUUUUUUU UUUUUUUU
EOF
