#!/bin/sh
. Common
$LEAVE

title "Set protection partially to W (partial byte), retrieve"
random_file _file
prog -w -b -5 -f - _file 2>_out <<EOF
WWWWWWWW WWWWWWW
EOF
prog -s -s >>_out
expect <<EOF
warning: padding incomplete protection byte with R
warning: padding protection bits to full Flash size with R
WWWWWWWW WWWWWWWR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR
WWWWWWWW WWWWWWWR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR
WWWWWWWW WWWWWWWR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR
WWWWWWWW WWWWWWWR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR
EOF
