#!/bin/sh
. Common
$LEAVE

title "Write Flash, then compare (okay)"
random_flash _flash
y_file _file
prog -w -b -5 _file
zero_file _file
prog_fail -c -b _file
expect <<EOF
comparison failed: block 0, byte 0: got 0x79, expected 0x00
EOF
