#!/bin/sh
. Common
$LEAVE

title "Write Flash, lock (W), then read (fail)"
random_flash _flash
random_file _file
prog -w -b -5 -F W _file
prog_fail -r -b _file
expect <<EOF
block 0 is read-protected
EOF
