#!/bin/sh
. Common

asm "ADC [X+expr],expr (carry, zero)" <<EOF
	adc	[x+0xff],0x90
	halt
EOF
sim <<EOF
ram[2] = 0x70
x = 3
run
ram[2]
CPU_F_Zero
CPU_F_Carry
.
@
EOF
expect <<EOF
HALT
0x0 0
0x1 1
0x1 1
0x4 4
0x13 19
EOF
