#!/bin/sh
. Common

asm "AND A,expr (carry remains set)" <<EOF
	and	a,0x13
	halt
EOF
sim <<EOF
a = 0x3e
CPU_F_Carry = 1
run
a
CPU_F_Zero
CPU_F_Carry
.
@
EOF
expect <<EOF
HALT
0x12 18
0x0 0
0x1 1
0x3 3
0xd 13
EOF
