#!/bin/sh
. Common

asm "Drive 1R, DR = 0" </dev/null
sim <<EOF
PRT0DM0 = 0xaa
PRT0DM1 = 0xcc
PRT0DM2 = 0xf0
PRT0DR = 0
P0 = 0xff r
PRT0DR
EOF
expect <<EOF
0x54 84
EOF

asm "Drive 1R, DR = 1" </dev/null
sim <<EOF
PRT0DM0 = 0xaa
PRT0DM1 = 0xcc
PRT0DM2 = 0xf0
PRT0DR = 0xff
P0 = 0xffR
PRT0DR
EOF
expect <<EOF
0xff 255
EOF
