#!/bin/sh
. Common

asm "Drive 1, DR = 0" </dev/null
sim <<EOF
PRT0DM0 = 0xaa
PRT0DM1 = 0xcc
PRT0DM2 = 0xf0
PRT0DR = 0
drive P0 = 0xff
PRT0DR
EOF
expect <<EOF
0x55 85
EOF

asm "Drive 1, DR = 1" </dev/null
sim <<EOF
PRT0DM0 = 0xaa
PRT0DM1 = 0xcc
PRT0DM2 = 0xf0
PRT0DR = 0xff
drive P0 = 0xff
PRT0DR
EOF
expect <<EOF
0xff 255
EOF
