#!/bin/sh
. Common

asm "Access RAM through a symbol" <<EOF
	area	data(ram)
	blk	1
foo:	blk	1
EOF
sim <<EOF
[foo] = 2
[foo]
[1]
EOF
expect <<EOF
0x2 2
0x2 2
EOF

asm "Access ROM through a symbol" <<EOF
	mov	[1],[2]
bar:	halt
EOF
sim <<EOF
rom[bar]
EOF
expect <<EOF
0x30 48
EOF

asm "Access a register through a symbol" <<EOF
blah:	equ	1
EOF
sim <<EOF
reg[1] = 3
reg[blah]
EOF
expect <<EOF
0x3 3
EOF
