#!/bin/sh
#
# Common - Elements shared by all regression tests for the M8C disassembler
#
# Written 2006 by Werner Almesberger
# Copyright 2006 Werner Almesberger
#


expect()
{
    echo -n "$1: " 1>&2
    cat >_ref
}


check_result()
{
    diff -u -w _ref _out >_diff || {
	echo FAILED "($SCRIPT)" 1>&2
	cat _diff 1>&2
	rm -f _ref _out _diff
	exit 1
    }
    echo PASSED 1>&2
    rm -f _ref _out _diff
    passed=`expr ${passed:-0} + 1`
}


m8cdas()
{
    ../m8cdas "$@" >_out || {
	echo FAILED "($SCRIPT)" 1>&2
	rm -f _ref _out
	exit 1
    }
    check_result
}


m8cdas_fail()
{
    ../m8cdas "$@" >_out 2>&1 && {
	echo FAILED "($SCRIPT)" 1>&2
	rm -f _ref _out
	exit 1
    }
    check_result
}


asdas_sym()
{
    ../../as/m8cas -m _map | ../m8cdas -m _map -s "$@" >_out || {
	echo FAILED "($SCRIPT)" 1>&2
	rm -f _ref _out _map
	exit 1
    }
    rm -f _map
    check_result
}


try_bare()
{
    expect "$1"
    shift
    m8cdas "$@"
}


try()
{
    title="$1"
    shift
    try_bare "$title" -s -e "$@"
}


fail_bare()
{
    expect "$1"
    shift
    m8cdas_fail "$@"
}


fail()
{
    title="$1"
    shift
    fail_bare "$title" -s -e "$@"
}
