#!/bin/sh
. Common

try "TST [expr],expr" 47 1 2 <<EOF
TST [0x01],0x02
EOF

try "TST [X+expr],expr" 48 2 4 <<EOF
TST [X+0x02],0x04
EOF

try "TST REG[expr],expr" 49 3 8 <<EOF
TST REG[0x03],0x08
EOF

try "TST REG[X+expr],expr" 4a 4 10 <<EOF
TST REG[X+0x04],0x10
EOF
