#!/bin/sh
. Common

asm "BLK" <<EOF
	nop
	area	ram(ram)
foo:
	blk	1
bar:
	blk	2
	area	rom(rom)
here:	mov	A,[foo]
	mov	A,[bar]
	db	here
EOF
expect <<EOF
40 51 00 51 01 01
EOF

asm "BLK (backward-defined)" <<EOF
	nop
foo:
	nop
	area	ram(ram)
bar:
	blk	foo
end:
	blk	0
	area	rom(rom)
	db	end
	nop
EOF
expect <<EOF
40 40 01 40
EOF

asm "BLK (self-reference)" <<EOF
	nop
	area	ram(ram)
	blk	2
foo:
	blk	foo
	area	rom(rom)
	db	foo
	nop
EOF
expect <<EOF
40 02 40
EOF

asm_fail "BLK (forward-defined)" <<EOF
	nop
	area	ram(ram)
	blk	foo
	area	rom(rom)
foo:
	nop
EOF
expect <<EOF
<stdin>:3: undefined identifier "foo"
EOF
