#!/bin/sh
. Common

asm "EQU local label" <<EOF
foo:	equ	10
	db	foo
EOF
expect <<EOF
0A
EOF

asm "EQU global label" <<EOF
foo::	equ	100
	dw	foo
EOF
expect <<EOF
00 64
EOF

asm "EQU reusable local label" <<EOF
.foo:	equ	1000
	dw	.foo
EOF
expect <<EOF
03 E8
EOF

asm "EQU forward expression" <<EOF
foo:	equ	bar+2
	dw	foo
bar:
EOF
expect <<EOF
00 04
EOF
