#!/bin/sh
. Common

asm "MVI A,[expr] (alternative syntax)" <<EOF
	mvi	a,[0x34]
	nop
EOF
expect <<EOF
3E 34 40
EOF

asm "MVI [expr],A (alternative syntax)" <<EOF
	mvi	[0x56],A
	nop
EOF
expect <<EOF
3F 56 40
EOF
