#!/bin/sh
. Common

asm_fail "Re-definable label are an extension (definition)" <<EOF
.1:
EOF
expect <<EOF
<stdin>:2: re-definable labels are a non-standard extension
EOF

asm_fail "Re-definable label are an extension (use)" <<EOF
	db	.1b
EOF
expect <<EOF
<stdin>:1: re-definable labels are a non-standard extension
EOF
