#!/bin/sh
. Common

sym "Symbol file, global label (data)" <<EOF
	area	data(ram)
	blk	4
foo::	blk	2
EOF
expect -w <<EOF
RAM  004  G foo  data  <stdin>:3
EOF

sym "Symbol file, global EQU" <<EOF
bar::	equ	100
EOF
expect -w <<EOF
EQU 0064  G  bar  -  <stdin>:2
EOF
